name: ExoPioneer Android Optimized Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android (Optimized)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.25f1
          targetPlatform: Android
          buildName: ExoPioneer
          buildPath: build/ExoPioneer.aab
          compressionMethod: LZ4
          androidExportType: aab
          androidKeystoreName: userDebug
          androidKeystorePass: debugpass
          androidKeyaliasName: debug
          androidKeyaliasPass: debugpass
          androidTargetSdkVersion: 33

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ExoPioneer-Android-AAB
          path: build/ExoPioneer.aab
