name: Request Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: 2022.3.25f1

      - name: Upload .alf file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: unity-activation-file.alf
name: Request Unity License
on:
  workflow_dispatch:

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create License Request File
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.17f1
