name: Build Android
uses: game-ci/unity-builder@v4
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
with:
  unityVersion: 2022.3.25f1
  targetPlatform: Android
  buildName: ExoPioneer
  buildPath: build/ExoPioneer.aab
  compressionMethod: LZ4
  androidExportType: aab
  androidKeystoreName: userDebug
  androidKeystorePass: debugpass
  androidKeyaliasName: debug
  androidKeyaliasPass: debugpass
  androidTargetSdkVersion: 33
