name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.25f1
          targetPlatform: Android
          buildName: ExoPioneer
          buildPath: build/android
      - uses: actions/upload-artifact@v3
        with:
          name: ExoPioneer-APK
          path: build/android
