name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Activate Unity License (Personal)
      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.10f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Step 3: Build Project
      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 2022.3.10f1
          projectPath: .
          buildName: ExoPioneer
          buildPath: build/Android

      # Step 4: Upload the built APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ExoPioneer-Android-APK
          path: build/Android/*.apk
