name: Unity Android Build (No License)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK (Skip License)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          allowDirtyBuild: true
          allowMissingLicense: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: build/Android
      
