name: Unity Android Build (Auto License)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}
          restore-keys: |
            Library-

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.20f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build Android
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.25f1
          targetPlatform: Android
          buildName: ExoPioneer
          outputPath: build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ExoPioneer-Android
          path: build
