name: Unity Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}
          restore-keys: |
            Library-

      - name: Setup Unity
        uses: game-ci/unity-actions/setup@v2
        with:
          unityVersion: 2022.3.0f1
          targetPlatform: Android

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/*.apk
