name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.17f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 2022.3.17f1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ExoPioneer-Android-APK
          path: build/Android/ExoPioneer.apk
