name: Unity License Request (Mobile)

on:
  workflow_dispatch:

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Request Unity Activation (.alf)
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.25f1
          targetPlatform: Android
