name: Unity License Request (Mobile)

on:
  workflow_dispatch:

jobs:
  requestLicense:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request Unity Activation File (.alf)
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.25f1
          targetPlatform: Android

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-Request
          path: unity-activation-file.alf
